#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

(
cd $OPENSHIFT_REPO_DIR
./scripts/import_budget_mongo.rb
./scripts/import_configuration.rb
)
